version: '3.9'

services:
  web:
    image: igor2022/business_card_site
    command: >
      bash -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn business_card_site.wsgi:application -c gunicorn_config.py"
    restart: always
    volumes:
      - ./media/:/usr/src/business_card_site/media/
      - ./staticfiles/:/usr/src/business_card_site/staticfiles/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    expose:
      - 8080
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    expose:
      - 5432

  
  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - /var/www/certbot:/var/www/certbot
      - ./media/:/usr/src/business_card_site/media/
      - ./staticfiles/:/usr/src/business_card_site/staticfiles/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/certbot/conf:/etc/letsencrypt/:rw
      - /var/certbot/www/:/var/www/certbot/:rw
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - nginx
volumes:
  postgres_data:
  
