# Generated by Django 5.1.1 on 2024-09-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_text', models.TextField(verbose_name='Текст для div (block5-text)')),
                ('p1_text', models.TextField(verbose_name='Текст для первого элемента p')),
                ('p2_text', models.TextField(verbose_name='Текст для второго элемента p')),
                ('p3_text', models.TextField(verbose_name='Текст для третьего элемента p')),
            ],
        ),
    ]
