# Generated by Django 5.1.1 on 2024-09-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card_app', '0004_gallery2_gallery3_gallery4_gallery5'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='biography_images/', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='URL видео'),
        ),
    ]
