# Generated by Django 5.1.1 on 2024-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card_app', '0005_biographyevent_alter_galleryimage_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
