# Generated by Django 5.1.1 on 2024-10-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card_app', '0006_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок (h5)')),
                ('description', models.TextField(verbose_name='Описание (p)')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='Изображение (img)')),
            ],
        ),
    ]
