# Generated by Django 5.1.1 on 2024-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card_app', '0007_eventblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventblock',
            name='button_text',
            field=models.CharField(default='ПОСМОТРЕТЬ', max_length=50, verbose_name='Текст кнопки'),
        ),
    ]
