# Generated by Django 5.1.1 on 2024-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card_app', '0009_remove_eventblock_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название видео')),
                ('video_mp4', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео (MP4)')),
                ('video_webm', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео (WEBM)')),
            ],
        ),
    ]
